sequenceDiagram
    participant process_files
    participant pre2post as converter.pre2post
    participant is_valid_expression as validate.is_valid_expression
    participant parser as parser.parse
    participant stack as stack.Stack

    process_files ->> pre2post: pass prefix expression
    pre2post ->> is_valid_expression: expression
    is_valid_expression ->> is_valid_expression: check
    is_valid_expression ->> pre2post: boolean
    pre2post ->> pre2post: raise ValueError if false
    pre2post ->> parser: expression
    parser ->> pre2post: expression as list of symbols
    loop for each symbol, accumulate postfix form
    pre2post ->> pre2post: call validate functions
    pre2post ->> stack: conditionally push
    stack ->> pre2post : conditionally pop
    end
    pre2post ->> pre2post: join postfix symbols into string
    pre2post ->> process_files: return postfix expression