sequenceDiagram
    participant pre2post as converter.pre2post
    participant is_valid_expression as validate.is_valid_expression
    participant parser as parser.parse
    participant num_operands_or_operations as num_operands & num_operations
    participant stack as stack.Stack
    participant parenthesesStack as stack.Stack for ()

    pre2post ->> is_valid_expression: pass expression and type (prefix or postfix)
    is_valid_expression ->> parser: pass expression and translate_symbols=True
    parser ->> parser: split expression into list, converting operands to ints
    parser ->> is_valid_expression: list of ints operands and str operations
    is_valid_expression ->> is_valid_expression: set direction by expression type
    loop for each symbol in expression
    is_valid_expression ->> is_valid_expression: short circuit if invalid state, return False
    is_valid_expression ->> parenthesesStack: conditionally push open parentheses
    parenthesesStack ->> is_valid_expression: conditionally pop
    is_valid_expression ->> stack: conditionally push operand or operation or result
    is_valid_expression ->> num_operands_or_operations: conditionally increment
    stack ->> is_valid_expression: conditionally pop
    end
    is_valid_expression ->> is_valid_expression: determine result (checking final constraints across variables)
    is_valid_expression ->> pre2post: return result