%% Encoding Flow

sequenceDiagram
    participant main
    participant io
    participant build as tree.build
    participant prioritize as tree.prioritize
    participant encode as encoding.encode
    participant normalize as encoding.normalize
    participant huffman as encoding.huffman
    
    main ->> io: Read cleartext, freq table
    alt
    else error
        io ->> main: raise error
        main ->> io: print message to stderr
    else success
        io ->> main: return cleartext, freq table rows
    end
    
    %% --------- %%
    main ->> build: call with freq table
    loop while more characters
        alt
        else ambiguous
            build ->> prioritize: get prioritization
            prioritize ->> build: return prioritization
        else
            build ->> build: build subtree
        end
    end
    
    %% --------- %%
    alt
    else error
        build ->> main: raise error
        main ->> io: print message to stderr
    else success
        build ->> main: return encoding tree
    end
    
    %% --------- %%
    loop for each line of cleartext
        main ->> encode: call with line, encoding tree 
        
        encode ->> normalize: call with line
        alt
        else error
            normalize ->> encode: raise error
            encode ->> main: raise error
            main ->> io: print message to stderr
        else success
            normalize ->> encode: return normalized line
        end
        loop for each char in line
            encode ->> encode: convert char to encoding with tree
            alt
            else error
                encode ->> encode: raise error
                encode ->> main: raise error
                main ->> io: print message to stderr
            else success
                encode ->> encode: append to internal buffer
            end
        end
        encode ->> main: return encoded cleartext
        main ->> io: write to encoded output file
        opt error
            io ->> main: raise error
            main ->> io: print message to stderr
        end
    end %% loop for each line of cleartext
    main ->> huffman: get string representation of encoding
    huffman ->> main: return string representation of encoding
    main ->> io: print representation
